"""
This type stub file was generated by pyright.
"""

def getAllTitles(): # -> list[str]:
    """Returns a list of strings of window titles for all visible windows.
    """
    ...

def getActiveWindow(): # -> LiteralString:
    """Returns a Window object of the currently active Window."""
    ...

def getWindowsAt(x, y): # -> list[Unknown]:
    ...

def activate(): # -> None:
    ...

def getWindowGeometry(title): # -> tuple[Unknown, Unknown, Unknown, Unknown] | None:
    ...

def isVisible(title): # -> None:
    ...

def isMinimized(): # -> None:
    ...

class MacOSWindow:
    def __init__(self, hWnd) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def close(self):
        """Closes this window. This may trigger "Are you sure you want to
        quit?" dialogs or other actions that prevent the window from
        actually closing. This is identical to clicking the X button on the
        window."""
        ...
    
    def minimize(self):
        """Minimizes this window."""
        ...
    
    def maximize(self):
        """Maximizes this window."""
        ...
    
    def restore(self):
        """If maximized or minimized, restores the window to it's normal size."""
        ...
    
    def activate(self):
        """Activate this window and make it the foreground window."""
        ...
    
    def resizeRel(self, widthOffset, heightOffset):
        """Resizes the window relative to its current size."""
        ...
    
    def resizeTo(self, newWidth, newHeight):
        """Resizes the window to a new width and height."""
        ...
    
    def moveRel(self, xOffset, yOffset):
        """Moves the window relative to its current position."""
        ...
    
    def moveTo(self, newLeft, newTop):
        """Moves the window to new coordinates on the screen."""
        ...
    
    @property
    def isMinimized(self):
        """Returns True if the window is currently minimized."""
        ...
    
    @property
    def isMaximized(self):
        """Returns True if the window is currently maximized."""
        ...
    
    @property
    def isActive(self):
        """Returns True if the window is currently the active, foreground window."""
        ...
    
    @property
    def title(self):
        """Returns the window title as a string."""
        ...
    
    @property
    def visible(self):
        ...
    


